### PR TITLE
Prune list of allowed payment code script types

### PR DESCRIPTION
**Pull request by justusranvier**
Define version 4 to signal lack of P2PK receiving support.

See issue #6

### CODE REVIEW

**Comment by justusranvier** [comment]
@SamouraiDev @craigraw

**Comment by justusranvier** [comment]
> We can't assume the the UI and underlying code will handle it easily or at all (most wallets configure a specific script type)
> We can't assume the server implementation will handle it easily or at all (most wallets use a server backend AFAIK - BIP157 is not widely used)

Most wallets require a complete architectural overhaul to support payment codes at all, whether they use a server backend or not. I'm fine with defining a separate version with only one script type for wallets that are restricted by the limitations of their server backend which is why I'm proposing version 4 in addition to version 3.

> Could you elaborate on why 20 bytes hashes aren't as secure in the context of derived keys - surely all public keys are derived?

Derived in this case means cases where two parties contribute to the derivation. It's easier for a party that provided data for the derivation to generate collisions than it would be for someone who was not involved.

> It's almost entirely unused currently, which makes it much more visible to blockchain analytics - this is a significant privacy concern and I can't see privacy focused wallets using it for this reason

The choice of script does not add extra identity data to the transaction. It is true that analytics can look at scripts and see which ones are P2PKH and which ones are P2PK but that difference doesn't tell them anything more about who the output belongs to.

In addition this argument is nullified by widespread usage of payment codes, so using it as an excuse to avoid rolling out payment codes in the first place is nonsensical circular reasoning.

>There is no way to derive an address from a P2PK script, which makes it more difficult to work with these outputs generally (outside of the context of this proposal)

What reason is there to work with these outputs outside the context of the sender's wallet and the receiver's wallet that necessitates an address format?

> I would like to request if version 4 could support receiving to P2WPKH only. This way, P2PKH wallets can use version 1 or 2, and P2WPKH wallets can use version 4. I think this would see a much higher chance of adoption given the significantly simpler implementation requirements, and avoidance of the privacy issue above.

As mentioned before, there are no valid privacy implications for using P2PK. Version 4 can be used by wallets with limited backend capabilities but the script type can't be specified as only P2WPKH because not all chains support that script type, but I can clarify this PR to emphasize that only P2PKH or P2WPKH is supported, depending on the chain.

> (Actually, I'd like to see version 3 support P2SH-P2WPKH (wrapped segwit) only, and version 4 P2WPKH only, to cover all common single sig script types, but I'd gladly take the above as a compromise).

If a version 4 is available for limited capability wallets to implement there is no reason to restrict version 3. A wallet that does not want to receive to a wider range of script types is not required to generate version 3 codes, and if sending to P2PK script is genuinely a problem for an implementation then it's not mandatory even if the recipient is version 3. It's allowed by the specification to send P2WPKH or P2PKH to a version 3 recipient.

Regarding P2SH-P2WPKH, what's the point? If there are still wallets in use that don't already support receiving native segwit, and also want to implement payment codes for some reason they should just implement both at the same time.

**Comment by craigraw** [comment]
> Most wallets require a complete architectural overhaul to support payment codes at all

I think this is probably why we have differed on some points, and also why BIP47 has had limited implementation to date. I agree significant changes are needed, but by avoiding multiple simultaneous script type support for a given wallet, perhaps not a complete overhaul (which will be prohibitive for many projects).

> It's easier for a party that provided data for the derivation to generate collisions than it would be for someone who was not involved.

Thanks, that's helpful to understand. How much easier is it?

> The choice of script does not add extra identity data to the transaction.

Yes, but it significantly decreases the anonymity set, which makes off-chain deductions more plausible. As a corollary, there has been much discussion on how Taproot scripts will initially have worse privacy than other common types, despite their other advantages, due to the initially smaller anonymity set.

> In addition this argument is nullified by widespread usage of payment codes

If this is too difficult for wallet developers to implement (as per your comment on 'complete architectural overhaul') then it's difficult to see how widespread usage happens. Which I guess it what we're working on in this PR :)

> What reason is there to work with these outputs outside the context of the sender's wallet and the receiver's wallet that necessitates an address format?

I think considering how the sender and receiver wallets display these outputs in their interfaces is valid. Some interfaces contain address/balance displays.

> I can clarify this PR to emphasize that only P2PKH or P2WPKH is supported, depending on the chain.

This works for me - as I understand the most recent change, on BTC, wallets receiving from version 4 payment codes need only listen to (and display) P2WPKH script types. Wallets receiving from version 1/2 payment codes need only listen to P2PKH script types.

> A wallet that does not want to receive to a wider range of script types is not required to generate version 3 codes

True, but it does make the landscape more complex for users looking to restore wallets on other software. I suspect version 3 payment codes will be less compatible across wallet software in future because of this.

> Regarding P2SH-P2WPKH, what's the point? If there are still wallets in use that don't already support receiving native segwit, and also want to implement payment codes for some reason they should just implement both at the same time.

It's less about wallet support, rather that the user's funds may in a P2SH-P2WPKH wallet, and without sweeping those funds into P2WPKH they may be unable to use version 4 payment codes on wallets that are configured to display P2SH-P2WPKH. It's not a major problem, just that payment code functionality may need to be disabled on those wallets depending on the implementation.

All that said, I'm happy with the changes made and feel version 4 is implementable for wallets that configure and listen for a specific script type.

**Comment by justusranvier** [comment]
> How much easier is it?

80 bits of work. This is mentioned in the specification.

> I think considering how the sender and receiver wallets display these outputs in their interfaces is valid. Some interfaces contain address/balance displays.

The simplest solution for a wallet is to display the payment code instead of the specific script element, or if that's not acceptable to just serialize the public key as base 58. It's up to the implementation to decide how to handle those issues. I'd recommend just showing the payment code.

> It's less about wallet support, rather that the user's funds may in a P2SH-P2WPKH wallet, and without sweeping those funds into P2WPKH they may be unable to use version 4 payment codes on wallets that are configured to display P2SH-P2WPKH.

I don't understand how that could possibly be a problem. Payment code recipients are only going to receive payments from senders whose wallets understand the payment code specification, because senders who don't understand the protocol can't generate notifications or destination scripts.

Regardless of whether the sender has existing utxos in P2SH-P2WPKH, P2PKH, P2WPKH, or any arbitrary script type that in no way limits the type of script they can generate for new outputs, so in what situation would they need to sweep?

**Comment by justusranvier** [comment]
> All that said, I'm happy with the changes made and feel version 4 is implementable for wallets that configure and listen for a specific script type.

I'm inclined to merge this change in that case, but ideally it would be good to hear from @SamouraiDev as well.

**Comment by SamouraiDev** [comment]
> > All that said, I'm happy with the changes made and feel version 4 is implementable for wallets that configure and listen for a specific script type.
> 
> I'm inclined to merge this change in that case, but ideally it would be good to hear from @SamouraiDev as well.

We are OK with these v3 & v4 changes Justus.

**Pull request merged**
