### PR TITLE
Add draft of version 3 payment codes as OBPP-05

### PR DESCRIPTION
**Pull request by justusranvier**

### CODE REVIEW

**Comment by SamouraiDev** [comment]
I'm having trouble replicating Alice's value of G for notification to Bob. Can you provide the intermediary values used in order to obtain P' ?

**Comment by justusranvier** [comment]
This is what I get for the Alice-to-Bob notification:

```
 a: 872313fe1beb41a9e1ae19c0def97591e5c204387b64b85f4077078b232906d0
 B: 023aeb8ccc72ff375de289993b87cc98c8f621ecca1e62b3747a76952bf71b7efe
Sx: 26fbb6e50a2b5a7c9a8607e1f0fd467cbe902746c5719e920bf2503c49f94cf8
 A: 0383b5e54776628baacee0cbb66b4db31aa95176dba1f62cabf0415103d0fdbda6
 s: 2a8948d3719a3b6780a145cec674a3304c26bf4505a8ce346cb0aa789f8df5bf192cea940d50ed2460301849f879037ef5669baf2ed5d769373f02027a7e3d3d
```

**Comment by justusranvier** [comment]
```
 P: 0302b85034fb08a8bfefd22848238257b252721454bbbfba2c3667f168837ea2cdad
P': 030292d97c287932848852890ded442311623e32ebfeba12e2020b41c2fbe12f3812
```

Now that I look at it there is an mistake in the spec because G should be bytes 1 - 33 of P' instead of bytes 0 - 32, other words G does not include the version byte.

**Comment by SamouraiDev** [comment]
Yes ;) I was getting to that.

**Comment by SamouraiDev** [comment]
I'm double checking on my end because I do not have the same pubkey for Bob's notification address.

**Comment by SamouraiDev** [comment]
For Bob's notification address 1ChvUUvht2hUQufHBXF8NgLhW8SwE2ecGV I have pubkey 024ce8e3b04ea205ff49f529950616c3db615b1e37753858cc60c1ce64d17e2ad8

**Comment by SamouraiDev** [comment]
I get the same results for A & F, as well as for the 3 payment code identifiers.

**Comment by justusranvier** [comment]
When interpreting Bob's payment code as an xpub I get:

```
        key: 029d125e1cb89e5a1a108192643ee25370c2e75c192b10aac18de8d5a09b5f48d5
 chain code: 3632ca6f76e23186143d9b372ed13b3e189bcd59a3ad301a9ce54e0484d0ffc9
```

The 0th non-hardened child is 023aeb8ccc72ff375de289993b87cc98c8f621ecca1e62b3747a76952bf71b7efe

**Comment by SamouraiDev** [comment]
OK, now I replicate.

**Comment by SamouraiDev** [comment]
Are you still on the other chat we had open ?

**Comment by justusranvier** [comment]
No, but I think I can ping you on Telegram.

**Comment by SamouraiDev** [comment]
As discussed a couple of weeks ago, we are replicating the test vectors.

**Pull request merged**
